## Add additional servos here by adding the pin, neutral and 
## range for each servo. Four servos are setup, as the Exomy
## Hat has 4 open slots
## The servo needs to be registered as well in the "src/servo.py"
## (exept the 4 existing ones)
## Be aware that adding a servo adds a value to the
## servo_angles message in "msg/ServoCommands.msg". You
## might need to adapt further code for example in the WebGui
## to control the servos.
## As every new message, deletes the settings for the other servos
## you need to set this in the coding.

# Pin numbers for servos on PWM board (99 stands for un-used servos)
pin_servo_1: 8
pin_servo_2: 99
pin_servo_3: 99
pin_servo_4: 99

## PWM values
# Those values highly depend on the motors and pwm board used
# Check out the wiki for further explanation

# PWM values for the neutral servo position
servo_pwm_neutral_1: 290
servo_pwm_neutral_2: 307
servo_pwm_neutral_3: 307
servo_pwm_neutral_4: 307

# PWM range around servo neutral position
servo_pwm_range_1: 183
servo_pwm_range_2: 185
servo_pwm_range_3: 185
servo_pwm_range_4: 185

# PWM offset to center in PWM values
servo_pwm_center_degree_offset_1: 0
servo_pwm_center_degree_offset_2: 0
servo_pwm_center_degree_offset_3: 0
servo_pwm_center_degree_offset_4: 0

# Servo limits in degree counted from neutal position
# Set maximum +-90 degree
# ccw: counter-clock wise
# cw: clock wise
# rotation looking at the drive shaft
servo_ccw_degree_1: -90
servo_ccw_degree_2: -90
servo_ccw_degree_3: -90
servo_ccw_degree_4: -90

servo_cw_degree_1: 90
servo_cw_degree_2: 90
servo_cw_degree_3: 90
servo_cw_degree_4: 90